name: Compila y Genera PDF

on:
  push:
jobs:
  compila:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with: dotnet-version:'9.0.x'
      - name: Instalar dependecias
        run: donet restore
      - name: Compilar
        run: dotnet build --no-restore
  crear-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Crear PDF
        uses: baileym02/markdown-pdf-action@v1.0.0
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: true
      - name: Subir PDF
        uses: actions/upload-artifact@v4.2.2
        with:
          name: docs
          path: pdfs
